---
- hosts: localhost
  remote_user: root
  tasks:
    - name: Launch spark cluster
      command: aws2 emr create-cluster --name "Spark cluster" --release-label emr-5.28.0 --applications Name=Spark Name=Zeppelin Name=Hadoop --ec2-attributes KeyName=gdeltKeyPair-educate --instance-type m5.xlarge --instance-count 6 --use-default-roles --log s3://fufu-program/logs --configurations "file://sparkConfiguration.json"
      register: spark_cluster_id

    - name: Wait for spark cluster running state
      command: aws2 emr wait cluster-running --cluster-id "{{ spark_cluster_id.stdout }}"

    - name: Set concurrency level
      command: aws2 emr modify-cluster --cluster-id "{{ spark_cluster_id.stdout }}" --step-concurrency-level 4